package com.etoc.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

import com.etoc.model.AreaInfo;

@Mapper
public interface AreaInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table area_info
	 * 
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	int deleteByPrimaryKey(String areaId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table area_info
	 * 
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	int insert(AreaInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table area_info
	 * 
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	int insertSelective(AreaInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table area_info
	 * 
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	AreaInfo selectByPrimaryKey(String areaId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table area_info
	 * 
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	int updateByPrimaryKeySelective(AreaInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table area_info
	 * 
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	int updateByPrimaryKey(AreaInfo record);

	// 查询区域管理信息分页
	List<AreaInfo> selectArea(Map<String, Object> query);

//	 //查询所有的地域信息
//	 List<AreaInfo> selectAll();
//	
//    //父级id及类型查询其子级地域信息
//    List<AreaInfo> selectSonAreaInfo(Map<String,Object> map);
//
//    //根据区域类型查询所有地区
//    List<AreaInfo> selectByAreaType(Map<String,Object> map);

	// 根据area条件查询地区集合
	List<AreaInfo> selectByAreaParms(Map<String, Object> map);

}