package com.etoc.mapper;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

import com.etoc.model.SystemInfo;



@Mapper
public interface SystemInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_info
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	int deleteByPrimaryKey(String systemId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_info
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	int insertSystemInfo(SystemInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_info
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	int insertSelective(SystemInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_info
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	SystemInfo selectBySystemId(String systemId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_info
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	int  updateSystemInfo(SystemInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_info
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	int updateByPrimaryKey(SystemInfo record);
	
	//根据键在字典表中查询全部平台类型
	List<SystemInfo> selectSystemInfosBySystemKey(String systemKey);
	//根据键和值在字典表中查询全部平台类型
	SystemInfo	selectSystemInfosBySystemKeyAndSystemVal(Map<String,Object> query);
    //28	分页查询系统参数管理
    List<SystemInfo> selectSystem(Map<String,Object> query);
    
    List<SystemInfo> selectBy (Map<String,Object> query);
	//根据键和名在字典表中查询全部平台类型
	SystemInfo getSystemInfosBySystemKeyAndSystemName(Map<String, Object> query);
     //根据键和名查找条数
	Integer selectKeyNameCount(Map<String, Object> query);
	 //根据键和值查找条数
	Integer selectKeyValCount(Map<String, Object> query);
}