package com.longer.dao.model;

public class SysOrganization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.id
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.code
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.name
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.priority
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.parent_code
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.parent_codes
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    private String parentCodes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.available
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    private String available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.id
     *
     * @return the value of sys_organization.id
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.id
     *
     * @param id the value for sys_organization.id
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.code
     *
     * @return the value of sys_organization.code
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.code
     *
     * @param code the value for sys_organization.code
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.name
     *
     * @return the value of sys_organization.name
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.name
     *
     * @param name the value for sys_organization.name
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.priority
     *
     * @return the value of sys_organization.priority
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.priority
     *
     * @param priority the value for sys_organization.priority
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.parent_code
     *
     * @return the value of sys_organization.parent_code
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.parent_code
     *
     * @param parentCode the value for sys_organization.parent_code
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.parent_codes
     *
     * @return the value of sys_organization.parent_codes
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    public String getParentCodes() {
        return parentCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.parent_codes
     *
     * @param parentCodes the value for sys_organization.parent_codes
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    public void setParentCodes(String parentCodes) {
        this.parentCodes = parentCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.available
     *
     * @return the value of sys_organization.available
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    public String getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.available
     *
     * @param available the value for sys_organization.available
     *
     * @mbg.generated Tue Jun 26 17:03:42 CST 2018
     */
    public void setAvailable(String available) {
        this.available = available;
    }
}