package com.longer.dao.model;

public class SysRoleResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.id
     *
     * @mbg.generated Wed Jun 27 15:31:04 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.role_id
     *
     * @mbg.generated Wed Jun 27 15:31:04 CST 2018
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.resource_id
     *
     * @mbg.generated Wed Jun 27 15:31:04 CST 2018
     */
    private String resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.id
     *
     * @return the value of sys_role_resource.id
     *
     * @mbg.generated Wed Jun 27 15:31:04 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.id
     *
     * @param id the value for sys_role_resource.id
     *
     * @mbg.generated Wed Jun 27 15:31:04 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.role_id
     *
     * @return the value of sys_role_resource.role_id
     *
     * @mbg.generated Wed Jun 27 15:31:04 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.role_id
     *
     * @param roleId the value for sys_role_resource.role_id
     *
     * @mbg.generated Wed Jun 27 15:31:04 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.resource_id
     *
     * @return the value of sys_role_resource.resource_id
     *
     * @mbg.generated Wed Jun 27 15:31:04 CST 2018
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.resource_id
     *
     * @param resourceId the value for sys_role_resource.resource_id
     *
     * @mbg.generated Wed Jun 27 15:31:04 CST 2018
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }
}