package com.longer.dao.model;

public class SystemInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_info.system_id
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	private String systemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_info.system_name
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	private String systemName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_info.system_key
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	private String systemKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_info.system_val
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	private String systemVal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_info.val_type
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	private String valType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_info.val_length
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	private Integer valLength;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_info.system_desc
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	private String systemDesc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_info.system_id
	 * @return  the value of system_info.system_id
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	public String getSystemId() {
		return systemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_info.system_id
	 * @param systemId  the value for system_info.system_id
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_info.system_name
	 * @return  the value of system_info.system_name
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	public String getSystemName() {
		return systemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_info.system_name
	 * @param systemName  the value for system_info.system_name
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	public void setSystemName(String systemName) {
		this.systemName = systemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_info.system_key
	 * @return  the value of system_info.system_key
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	public String getSystemKey() {
		return systemKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_info.system_key
	 * @param systemKey  the value for system_info.system_key
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	public void setSystemKey(String systemKey) {
		this.systemKey = systemKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_info.system_val
	 * @return  the value of system_info.system_val
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	public String getSystemVal() {
		return systemVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_info.system_val
	 * @param systemVal  the value for system_info.system_val
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	public void setSystemVal(String systemVal) {
		this.systemVal = systemVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_info.val_type
	 * @return  the value of system_info.val_type
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	public String getValType() {
		return valType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_info.val_type
	 * @param valType  the value for system_info.val_type
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	public void setValType(String valType) {
		this.valType = valType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_info.val_length
	 * @return  the value of system_info.val_length
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	public Integer getValLength() {
		return valLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_info.val_length
	 * @param valLength  the value for system_info.val_length
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	public void setValLength(Integer valLength) {
		this.valLength = valLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_info.system_desc
	 * @return  the value of system_info.system_desc
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	public String getSystemDesc() {
		return systemDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_info.system_desc
	 * @param systemDesc  the value for system_info.system_desc
	 * @mbg.generated  Thu Jun 28 11:41:03 CST 2018
	 */
	public void setSystemDesc(String systemDesc) {
		this.systemDesc = systemDesc;
	}
}