package com.longer.dao.model;

public class SysUserResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_resource.id
     *
     * @mbg.generated Wed Jun 27 15:41:31 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_resource.user_id
     *
     * @mbg.generated Wed Jun 27 15:41:31 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_resource.resource_id
     *
     * @mbg.generated Wed Jun 27 15:41:31 CST 2018
     */
    private String resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_resource.id
     *
     * @return the value of sys_user_resource.id
     *
     * @mbg.generated Wed Jun 27 15:41:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_resource.id
     *
     * @param id the value for sys_user_resource.id
     *
     * @mbg.generated Wed Jun 27 15:41:31 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_resource.user_id
     *
     * @return the value of sys_user_resource.user_id
     *
     * @mbg.generated Wed Jun 27 15:41:31 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_resource.user_id
     *
     * @param userId the value for sys_user_resource.user_id
     *
     * @mbg.generated Wed Jun 27 15:41:31 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_resource.resource_id
     *
     * @return the value of sys_user_resource.resource_id
     *
     * @mbg.generated Wed Jun 27 15:41:31 CST 2018
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_resource.resource_id
     *
     * @param resourceId the value for sys_user_resource.resource_id
     *
     * @mbg.generated Wed Jun 27 15:41:31 CST 2018
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }
}