package com.etoc.mapper;

import com.etoc.model.LoginUser;

public interface LoginUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Wed May 01 20:08:29 CST 2019
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Wed May 01 20:08:29 CST 2019
	 */
	int insert(LoginUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Wed May 01 20:08:29 CST 2019
	 */
	int insertSelective(LoginUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Wed May 01 20:08:29 CST 2019
	 */
	LoginUser selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Wed May 01 20:08:29 CST 2019
	 */
	int updateByPrimaryKeySelective(LoginUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Wed May 01 20:08:29 CST 2019
	 */
	int updateByPrimaryKey(LoginUser record);
}