package com.etoc.model;

public class AreaInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column area_info.area_id
	 * 
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	private String areaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column area_info.area_name
	 * 
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	private String areaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column area_info.area_type
	 * 
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	private Integer areaType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column area_info.countries_id
	 * 
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	private String countriesId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column area_info.area_id
	 * 
	 * @return the value of area_info.area_id
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	public String getAreaId() {
		return areaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column area_info.area_id
	 * 
	 * @param areaId the value for area_info.area_id
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column area_info.area_name
	 * 
	 * @return the value of area_info.area_name
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	public String getAreaName() {
		return areaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column area_info.area_name
	 * 
	 * @param areaName the value for area_info.area_name
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column area_info.area_type
	 * 
	 * @return the value of area_info.area_type
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	public Integer getAreaType() {
		return areaType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column area_info.area_type
	 * 
	 * @param areaType the value for area_info.area_type
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	public void setAreaType(Integer areaType) {
		this.areaType = areaType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column area_info.countries_id
	 * 
	 * @return the value of area_info.countries_id
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	public String getCountriesId() {
		return countriesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column area_info.countries_id
	 * 
	 * @param countriesId the value for area_info.countries_id
	 * @mbg.generated Thu Jun 28 15:25:01 CST 2018
	 */
	public void setCountriesId(String countriesId) {
		this.countriesId = countriesId;
	}
}