package com.etoc.model;

public class SysResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.id
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.code
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.name
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.type
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.system_type
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    private Integer systemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.icon
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.priority
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.url
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.parent_code
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.parent_codes
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    private String parentCodes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.permission
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.available
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    private String available;
    
    /**
     * 是否是叶子节点
     */
    private Integer isLeaf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.id
     *
     * @return the value of sys_resource.id
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.id
     *
     * @param id the value for sys_resource.id
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.code
     *
     * @return the value of sys_resource.code
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.code
     *
     * @param code the value for sys_resource.code
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.name
     *
     * @return the value of sys_resource.name
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.name
     *
     * @param name the value for sys_resource.name
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.type
     *
     * @return the value of sys_resource.type
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.type
     *
     * @param type the value for sys_resource.type
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.system_type
     *
     * @return the value of sys_resource.system_type
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public Integer getSystemType() {
        return systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.system_type
     *
     * @param systemType the value for sys_resource.system_type
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public void setSystemType(Integer systemType) {
        this.systemType = systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.icon
     *
     * @return the value of sys_resource.icon
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.icon
     *
     * @param icon the value for sys_resource.icon
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.priority
     *
     * @return the value of sys_resource.priority
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.priority
     *
     * @param priority the value for sys_resource.priority
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.url
     *
     * @return the value of sys_resource.url
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.url
     *
     * @param url the value for sys_resource.url
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.parent_code
     *
     * @return the value of sys_resource.parent_code
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.parent_code
     *
     * @param parentCode the value for sys_resource.parent_code
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.parent_codes
     *
     * @return the value of sys_resource.parent_codes
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public String getParentCodes() {
        return parentCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.parent_codes
     *
     * @param parentCodes the value for sys_resource.parent_codes
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public void setParentCodes(String parentCodes) {
        this.parentCodes = parentCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.permission
     *
     * @return the value of sys_resource.permission
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.permission
     *
     * @param permission the value for sys_resource.permission
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.available
     *
     * @return the value of sys_resource.available
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public String getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.available
     *
     * @param available the value for sys_resource.available
     *
     * @mbg.generated Wed Jun 27 15:55:59 CST 2018
     */
    public void setAvailable(String available) {
        this.available = available;
    }

	public Integer getIsLeaf()
	{
		return isLeaf;
	}

	public void setIsLeaf(Integer isLeaf)
	{
		this.isLeaf = isLeaf;
	}
    
    
}