package com.etoc.model;

import java.util.Date;

public class SystemLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.id
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.user_id
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.user_name
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.req_ip
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private String reqIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.req_url
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private String reqUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.log_level
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private Integer logLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.modual
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private String modual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.desc
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private String logDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.method
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.log_type
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private Integer logType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.exceptions
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private String exceptions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.serial
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private String serial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.terminal
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private Integer terminal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.creater
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.create_time
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.updater
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.update_time
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.params
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    private String params;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.id
     *
     * @return the value of system_log.id
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.id
     *
     * @param id the value for system_log.id
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.user_id
     *
     * @return the value of system_log.user_id
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.user_id
     *
     * @param userId the value for system_log.user_id
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.user_name
     *
     * @return the value of system_log.user_name
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.user_name
     *
     * @param userName the value for system_log.user_name
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.req_ip
     *
     * @return the value of system_log.req_ip
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public String getReqIp() {
        return reqIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.req_ip
     *
     * @param reqIp the value for system_log.req_ip
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setReqIp(String reqIp) {
        this.reqIp = reqIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.req_url
     *
     * @return the value of system_log.req_url
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public String getReqUrl() {
        return reqUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.req_url
     *
     * @param reqUrl the value for system_log.req_url
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setReqUrl(String reqUrl) {
        this.reqUrl = reqUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.log_level
     *
     * @return the value of system_log.log_level
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public Integer getLogLevel() {
        return logLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.log_level
     *
     * @param logLevel the value for system_log.log_level
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setLogLevel(Integer logLevel) {
        this.logLevel = logLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.modual
     *
     * @return the value of system_log.modual
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public String getModual() {
        return modual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.modual
     *
     * @param modual the value for system_log.modual
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setModual(String modual) {
        this.modual = modual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.desc
     *
     * @return the value of system_log.desc
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    
    public String getLogDesc() {
		return this.logDesc;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.desc
     *
     * @param desc the value for system_log.desc
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    
    public void setLogDesc(String logDesc) {
		this.logDesc = logDesc;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.method
     *
     * @return the value of system_log.method
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public String getMethod() {
        return method;
    }


	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.method
     *
     * @param method the value for system_log.method
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.log_type
     *
     * @return the value of system_log.log_type
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public Integer getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.log_type
     *
     * @param logType the value for system_log.log_type
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setLogType(Integer logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.exceptions
     *
     * @return the value of system_log.exceptions
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public String getExceptions() {
        return exceptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.exceptions
     *
     * @param exceptions the value for system_log.exceptions
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setExceptions(String exceptions) {
        this.exceptions = exceptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.serial
     *
     * @return the value of system_log.serial
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.serial
     *
     * @param serial the value for system_log.serial
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setSerial(String serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.terminal
     *
     * @return the value of system_log.terminal
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public Integer getTerminal() {
        return terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.terminal
     *
     * @param terminal the value for system_log.terminal
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setTerminal(Integer terminal) {
        this.terminal = terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.creater
     *
     * @return the value of system_log.creater
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.creater
     *
     * @param creater the value for system_log.creater
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.create_time
     *
     * @return the value of system_log.create_time
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.create_time
     *
     * @param createTime the value for system_log.create_time
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.updater
     *
     * @return the value of system_log.updater
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.updater
     *
     * @param updater the value for system_log.updater
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.update_time
     *
     * @return the value of system_log.update_time
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.update_time
     *
     * @param updateTime the value for system_log.update_time
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.params
     *
     * @return the value of system_log.params
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.params
     *
     * @param params the value for system_log.params
     *
     * @mbg.generated Wed Aug 15 16:51:54 CST 2018
     */
    public void setParams(String params) {
        this.params = params;
    }
}