/*
 * 文 件 名:  SysUserGroupController.java
 * 版    权:  ETOC 信息技术有限公司, Ltd. Copyright YYYY-YYYY,  All rights reserved
 * 描    述:  <描述>
 * 修 改 人:  longlong
 * 修改时间:  2018年8月14日
 * 跟踪单号:  <跟踪单号>
 * 修改单号:  <修改单号>
 * 修改内容:  <修改内容>
 */
package com.etoc.model;
/**
 * 用户组
 * @author  longlong
 * @version  [版本号, 2018年8月14日]
 * @see  [相关类/方法]
 * @since  [产品/模块版本]
 */
public class SysUserGroup {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_usergroup.id
	 * @mbg.generated  Tue Aug 14 20:41:08 CST 2018
	 */
	private  String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_usergroup.group_name
	 * @mbg.generated  Tue Aug 14 20:41:08 CST 2018
	 */
	private String groupName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_usergroup.description
	 * @mbg.generated  Tue Aug 14 20:41:08 CST 2018
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_usergroup.available
	 * @mbg.generated  Tue Aug 14 20:41:08 CST 2018
	 */
	private String available;

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAvailable() {
		return this.available;
	}

	public void setAvailable(String available) {
		this.available = available;
	}

	
}
