package com.etoc.model;

import java.util.Date;

public class SysUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.organization_id
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    private String organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.department_id
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    private String departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login_name
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login_psw
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    private String loginPsw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.salt
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login_time
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_time
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_mobile
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    private String userMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_mail
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    private String userMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_wechat
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    private String userWechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_note
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    private String userNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.status
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.organization_id
     *
     * @return the value of sys_user.organization_id
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.organization_id
     *
     * @param organizationId the value for sys_user.organization_id
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.department_id
     *
     * @return the value of sys_user.department_id
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.department_id
     *
     * @param departmentId the value for sys_user.department_id
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.login_name
     *
     * @return the value of sys_user.login_name
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.login_name
     *
     * @param loginName the value for sys_user.login_name
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.login_psw
     *
     * @return the value of sys_user.login_psw
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public String getLoginPsw() {
        return loginPsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.login_psw
     *
     * @param loginPsw the value for sys_user.login_psw
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public void setLoginPsw(String loginPsw) {
        this.loginPsw = loginPsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.salt
     *
     * @return the value of sys_user.salt
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.salt
     *
     * @param salt the value for sys_user.salt
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.login_time
     *
     * @return the value of sys_user.login_time
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.login_time
     *
     * @param loginTime the value for sys_user.login_time
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param userName the value for sys_user.user_name
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_time
     *
     * @return the value of sys_user.create_time
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_time
     *
     * @param createTime the value for sys_user.create_time
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_mobile
     *
     * @return the value of sys_user.user_mobile
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_mobile
     *
     * @param userMobile the value for sys_user.user_mobile
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_mail
     *
     * @return the value of sys_user.user_mail
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_mail
     *
     * @param userMail the value for sys_user.user_mail
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_wechat
     *
     * @return the value of sys_user.user_wechat
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public String getUserWechat() {
        return userWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_wechat
     *
     * @param userWechat the value for sys_user.user_wechat
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public void setUserWechat(String userWechat) {
        this.userWechat = userWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_note
     *
     * @return the value of sys_user.user_note
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public String getUserNote() {
        return userNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_note
     *
     * @param userNote the value for sys_user.user_note
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public void setUserNote(String userNote) {
        this.userNote = userNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.status
     *
     * @return the value of sys_user.status
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.status
     *
     * @param status the value for sys_user.status
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }
}