package com.etoc.model;

public class SysUrlFilter {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_url_filter.id
	 * 
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_url_filter.name
	 * 
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_url_filter.method
	 * 
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public String method;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_url_filter.url
	 * 
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_url_filter.roles
	 * 
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public String roles;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_url_filter.permissions
	 * 
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public String permissions;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_url_filter.id
	 * 
	 * @return the value of sys_url_filter.id
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_url_filter.id
	 * 
	 * @param id the value for sys_url_filter.id
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_url_filter.name
	 * 
	 * @return the value of sys_url_filter.name
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_url_filter.name
	 * 
	 * @param name the value for sys_url_filter.name
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_url_filter.method
	 * 
	 * @return the value of sys_url_filter.method
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public String getMethod() {
		return method;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_url_filter.method
	 * 
	 * @param method the value for sys_url_filter.method
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public void setMethod(String method) {
		this.method = method;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_url_filter.url
	 * 
	 * @return the value of sys_url_filter.url
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_url_filter.url
	 * 
	 * @param url the value for sys_url_filter.url
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_url_filter.roles
	 * 
	 * @return the value of sys_url_filter.roles
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public String getRoles() {
		return roles;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_url_filter.roles
	 * 
	 * @param roles the value for sys_url_filter.roles
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public void setRoles(String roles) {
		this.roles = roles;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_url_filter.permissions
	 * 
	 * @return the value of sys_url_filter.permissions
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public String getPermissions() {
		return permissions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_url_filter.permissions
	 * 
	 * @param permissions the value for sys_url_filter.permissions
	 * @mbg.generated Tue Aug 14 20:36:17 CST 2018
	 */
	public void setPermissions(String permissions) {
		this.permissions = permissions;
	}

}