package com.etoc.model;

public class LoginUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.user_id
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.user_name
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.salt
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.user_password
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.role_id
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.user_id
     *
     * @return the value of login_user.user_id
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.user_id
     *
     * @param userId the value for login_user.user_id
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.user_name
     *
     * @return the value of login_user.user_name
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.user_name
     *
     * @param userName the value for login_user.user_name
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.salt
     *
     * @return the value of login_user.salt
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.salt
     *
     * @param salt the value for login_user.salt
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.user_password
     *
     * @return the value of login_user.user_password
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.user_password
     *
     * @param userPassword the value for login_user.user_password
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.role_id
     *
     * @return the value of login_user.role_id
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.role_id
     *
     * @param roleId the value for login_user.role_id
     *
     * @mbg.generated Wed May 01 20:07:41 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}