dubbo:
  scan:
    base-packages: com.etoc.service.impl
  application:
    name: dubbo-provider-demo
    id: dubbo-provider-demo
  protocol:
      name: dubbo
      port: 20880
  registry:
    address: zookeeper://192.168.1.10:2181
    check: false