server: 
  port: 9001

#eureka: 
#  server:#     enable-self-preservation: false #关掉自我保护机制 宁杀错不放过
#  client: 
#    register-with-eureka: false                  #false表示不向注册中心注册自己。
#    fetch-registry: false                        #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
#    service-url: 
#      defaultZone: http://localhost:9000/eureka/ #此处为单节点的注册中心配置,多节点的应指向其他eureka server地址,逗号分隔,且前面2个配置均为true


eureka: 
  instance:
    hostname: eureka9001.com #eureka服务端的实例名称
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka9002.com:9002/eureka/,http://eureka9003.com:9003/eureka

