package com.longer.dao.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

import com.longer.dao.model.SysUserResource;

@Mapper
public interface SysUserResourceMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user_resource
	 *
	 * @mbg.generated Wed Jun 27 15:41:31 CST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user_resource
	 *
	 * @mbg.generated Wed Jun 27 15:41:31 CST 2018
	 */
	int insert(SysUserResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user_resource
	 *
	 * @mbg.generated Wed Jun 27 15:41:31 CST 2018
	 */
	int insertSelective(SysUserResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user_resource
	 *
	 * @mbg.generated Wed Jun 27 15:41:31 CST 2018
	 */
	SysUserResource selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user_resource
	 *
	 * @mbg.generated Wed Jun 27 15:41:31 CST 2018
	 */
	int updateByPrimaryKeySelective(SysUserResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user_resource
	 *
	 * @mbg.generated Wed Jun 27 15:41:31 CST 2018
	 */
	int updateByPrimaryKey(SysUserResource record);

	// 根据用户ID查询关联表信息
	List<SysUserResource> selectBySysResourceModel(Map<String, Object> map);

	// 删除关联信息
	int deleteSysUserResourceModel(Map<String, Object> map);

}