package com.longer.dao.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

import com.longer.dao.model.SysUser;

@Mapper
public interface SysUserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user
	 *
	 * @mbg.generated Thu May 31 14:36:30 CST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user
	 *
	 * @mbg.generated Thu May 31 14:36:30 CST 2018
	 */
	int insert(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user
	 *
	 * @mbg.generated Thu May 31 14:36:30 CST 2018
	 */
	int insertSelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user
	 *
	 * @mbg.generated Thu May 31 14:36:30 CST 2018
	 */
	SysUser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user
	 *
	 * @mbg.generated Thu May 31 14:36:30 CST 2018
	 */
	// 部分修改
	int updateByPrimaryKeySelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user
	 *
	 * @mbg.generated Thu May 31 14:36:30 CST 2018
	 */
//	int updateByPrimaryKey(SysUser record);

	// 根据登录名和id查询用户（包括删除用户 ）
	SysUser selectByQuery(Map<String, Object> query);

	// 分页 根据模糊条件查询user用户信息
	List<SysUser> selectByLikeQuery(Map<String, Object> query);

	// 根据userID或roleId或userGroupID联合中间表查询用户集
	List<SysUser> selectByQueryId(Map<String, Object> map);

}