package com.deepexi.model;

public class Assembly {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assembly.assembly_id
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	private Integer assemblyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assembly.assembly_type
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	private Integer assemblyType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assembly.assembly_version
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	private String assemblyVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assembly.available
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	private String available;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assembly.assembly_id
	 * @return  the value of assembly.assembly_id
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	public Integer getAssemblyId() {
		return assemblyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assembly.assembly_id
	 * @param assemblyId  the value for assembly.assembly_id
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	public void setAssemblyId(Integer assemblyId) {
		this.assemblyId = assemblyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assembly.assembly_type
	 * @return  the value of assembly.assembly_type
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	public Integer getAssemblyType() {
		return assemblyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assembly.assembly_type
	 * @param assemblyType  the value for assembly.assembly_type
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	public void setAssemblyType(Integer assemblyType) {
		this.assemblyType = assemblyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assembly.assembly_version
	 * @return  the value of assembly.assembly_version
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	public String getAssemblyVersion() {
		return assemblyVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assembly.assembly_version
	 * @param assemblyVersion  the value for assembly.assembly_version
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	public void setAssemblyVersion(String assemblyVersion) {
		this.assemblyVersion = assemblyVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assembly.available
	 * @return  the value of assembly.available
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	public String getAvailable() {
		return available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assembly.available
	 * @param available  the value for assembly.available
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	public void setAvailable(String available) {
		this.available = available;
	}
}