package com.deepexi.model;

public class AssemblyType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assembly_type.id
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column assembly_type.name
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assembly_type.id
	 * @return  the value of assembly_type.id
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assembly_type.id
	 * @param id  the value for assembly_type.id
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column assembly_type.name
	 * @return  the value of assembly_type.name
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column assembly_type.name
	 * @param name  the value for assembly_type.name
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}
}