package com.etoc.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.etoc.model.SysUser;



@Mapper
public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    SysUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu May 31 14:36:30 CST 2018
     */
    int updateByPrimaryKey(SysUser record);
    
    //根据完整条件查询user用户信息
    SysUser selectByFullQuery(SysUser user);
    
    // 根据用户名查询用户信息
    SysUser selectByUserName(SysUser user);
    
    //根据用所有的用户名
    List<SysUser> selectUserNamesByIds();
    
    //根据条件查询用户条数（包括删除用户 ）
    Integer selectByQuery(SysUser user);
    
    //批量修改用户状态
    Integer updateBatchStatus(@Param("userIds")String userIds,@Param("status")Integer status);
    
    //根据模糊条件查询user用户信息
    List<SysUser> selectByLikeQuery(SysUser user);
    
}