package com.deepexi.mapper;

import com.deepexi.model.AssemblyType;

public interface AssemblyTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assembly_type
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assembly_type
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	int insert(AssemblyType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assembly_type
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	int insertSelective(AssemblyType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assembly_type
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	AssemblyType selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assembly_type
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	int updateByPrimaryKeySelective(AssemblyType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assembly_type
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	int updateByPrimaryKey(AssemblyType record);
}