package com.deepexi.mapper;

import com.deepexi.model.Assembly;

public interface AssemblyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assembly
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	int deleteByPrimaryKey(Integer assemblyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assembly
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	int insert(Assembly record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assembly
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	int insertSelective(Assembly record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assembly
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	Assembly selectByPrimaryKey(Integer assemblyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assembly
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	int updateByPrimaryKeySelective(Assembly record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table assembly
	 * @mbg.generated  Tue Jun 25 20:13:01 CST 2019
	 */
	int updateByPrimaryKey(Assembly record);
}