server:
   port: 8085
#eureka:
#  client: #客户端注册进eureka服务列表内
#    service-url: 
#     defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/,http://localhost:9003/eureka
#  instance:
##    instance-id: springcloud-api   #自定义服务名称信息
#    prefer-ip-address: true     #访问路径可以显示IP地址   
spring:
  application:
    name: system-manager
#  jackson:
#    default-property-inclusion: non_empty
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
#    multipart:
#      max-file-size: 50Mb
#      max-request-size: 50Mb
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  datasource:
    master:
      jdbcUrl: jdbc:mysql://192.168.1.5:3306/test2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      jdbcUrl: jdbc:mysql://192.168.1.10:3339/test2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
      username: longer   # 只读账户
      password: longer
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
  type-aliases-package: com.longer.dao.model

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
    
#对当前服务的重试次数
#ribbon: 
#  MaxAutoRetries: 0
##切换相同Server的次数
#  MaxAutoRetriesNextServer: 0
#  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
#  ReadTimeout: 500000
####指的是建立连接后从服务器读取到可用资源所用的时间。 
#  ConnectTimeout: 500000     
#  eureka:
#    enabled: true          